# Generated by Django 5.0.1 on 2024-02-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_pr_quantity',
            new_name='user_product_quantity',
        ),
    ]
